# Builder
FROM ubuntu:22.04 as base

ARG VERSION
WORKDIR /app
COPY . .

RUN apt-get update
RUN apt-get install -y wget build-essential ca-certificates
RUN wget https://go.dev/dl/go1.21.3.linux-arm64.tar.gz

ENV GOROOT /usr/local/go
ENV GOPATH /go
ENV PATH /usr/local/go/bin:/go/bin:$PATH
ENV GOBIN /service/bin

RUN tar -xvf go1.20.5.linux-arm64.tar.gz
RUN mv go /usr/local

RUN CGO_ENABLED=0 GOOS=linux go mod tidy 
RUN CGO_ENABLED=0 GOOS=linux go mod vendor 
RUN CGO_ENABLED=0 GOOS=linux go build -o hyperdot-node cmd/node/main.go

# Runtime
FROM alpine:3.18.4

WORKDIR /app

COPY --from=builder /app/hyperdot-node .

EXPOSE 3030

ENV HYPETDOT_NODE_CONFIG /app/config/hyperdot.json
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/config/hyperdot-gcloud-iam.json

COPY ./config/hyperdot.json /app/config/hyperdot.json
COPY ./config/hyperdot-gcloud-iam.json /app/config/hyperdot-gcloud-iam.json

CMD ["./hyperdot-node", "-config=/app/config/hyperdot.json"]
