version: '3'
services:
  postgres:
    image: postgres:16rc1
    container_name: hyperdot-postgres
    environment:
      POSTGRES_DB: hyperdot
      POSTGRES_USER: hyperdot
      POSTGRES_PASSWORD: hyperdot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/hyperdot/postgres/data

  redis:
    image: redis:7
    container_name: hyperdot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/hyperdot/redis/data

volumes:
  postgres_data:
  redis_data:

